# Generated by Django 6.0 on 2026-01-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kaggle_slug",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Уникальный идентификатор контеста",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Название соревнования"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Срок окончания"
                    ),
                ),
                (
                    "participant_count",
                    models.IntegerField(
                        blank=True, verbose_name="Количество участников"
                    ),
                ),
            ],
            options={
                "db_table": "contest",
            },
        ),
        migrations.CreateModel(
            name="KaggleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=50, verbose_name="Никнейм на платформе"
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="Уровень мастерства"
                    ),
                ),
                (
                    "registered",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время сохранения таблицы"
                    ),
                ),
                ("data", models.JSONField(verbose_name="Данные лидерборда")),
                (
                    "contest_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dash_board.contest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantContest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(blank=True, verbose_name="Очки рейтинга")),
                (
                    "position",
                    models.IntegerField(verbose_name="Позиция в таблице лидеров"),
                ),
                ("submissions", models.IntegerField(verbose_name="Количество посылок")),
                (
                    "last_submission",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последней отправки"
                    ),
                ),
                (
                    "contest_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dash_board.contest",
                    ),
                ),
                (
                    "kaggle_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dash_board.kaggleuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="kaggleuser",
            name="contests",
            field=models.ManyToManyField(
                through="dash_board.ParticipantContest", to="dash_board.contest"
            ),
        ),
    ]
