# Generated by Django 6.0 on 2026-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="description",
            field=models.CharField(default="", max_length=200, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="contest",
            name="prize",
            field=models.CharField(
                default="", max_length=20, verbose_name="Вознаграждение"
            ),
            preserve_default=False,
        ),
    ]
