# Generated by Django 6.0 on 2026-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0002_contest_description_contest_prize"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kaggleuser",
            old_name="user_name",
            new_name="user_slug",
        ),
        migrations.RemoveField(
            model_name="kaggleuser",
            name="registered",
        ),
        migrations.RemoveField(
            model_name="kaggleuser",
            name="skill_level",
        ),
        migrations.RemoveField(
            model_name="participantcontest",
            name="last_submission",
        ),
        migrations.RemoveField(
            model_name="participantcontest",
            name="submissions",
        ),
        migrations.AddField(
            model_name="contest",
            name="image_url",
            field=models.CharField(
                default="", max_length=500, verbose_name="Ссылка на картинку"
            ),
        ),
        migrations.AddField(
            model_name="participantcontest",
            name="saved_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время сохранения участника соревнования"
            ),
        ),
        migrations.AlterModelTable(
            name="kaggleuser",
            table="kaggle_user",
        ),
        migrations.AlterModelTable(
            name="leaderboard",
            table="leaderboard",
        ),
        migrations.AlterModelTable(
            name="participantcontest",
            table="participant_contest",
        ),
    ]
