# Generated by Django 6.0 on 2026-01-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0003_rename_user_name_kaggleuser_user_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest",
            old_name="kaggle_slug",
            new_name="competition_slug",
        ),
    ]
