# Generated by Django 6.0 on 2026-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0004_rename_kaggle_slug_contest_competition_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="version",
            field=models.IntegerField(
                default=1, verbose_name="Версия записи позиций в лидерборде"
            ),
            preserve_default=False,
        ),
    ]
