# Generated by Django 6.0 on 2026-01-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0005_leaderboard_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantcontest",
            name="kaggle_user_id",
        ),
        migrations.RemoveField(
            model_name="participantcontest",
            name="contest_id",
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_slug",
                    models.CharField(max_length=50, verbose_name="Название команды"),
                ),
                ("team_id", models.IntegerField(verbose_name="Айди команды")),
                ("contests", models.ManyToManyField(to="dash_board.contest")),
            ],
            options={
                "db_table": "kaggle_team",
            },
        ),
        migrations.DeleteModel(
            name="KaggleUser",
        ),
        migrations.DeleteModel(
            name="ParticipantContest",
        ),
    ]
