# Generated by Django 6.0 on 2026-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash_board", "0006_remove_participantcontest_kaggle_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="organization_name",
            field=models.CharField(
                default="",
                max_length=200,
                verbose_name="Название организации, проводящей контест",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="organization_ref",
            field=models.CharField(
                default="", max_length=500, verbose_name="Слаг организации"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="url",
            field=models.CharField(
                default="", max_length=500, verbose_name="Ссылка на контест на кагле"
            ),
        ),
    ]
